name: Run Python Script on .md change

on:
  push:
    paths:
      - '**/*.md'

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    env:
      CONF_USER: '${{ secrets.CONF_USER }}'
      CONF_TOKEN: '${{ secrets.CONF_TOKEN }}' 


    defaults:
      run:
        working-directory: ./.github/confluence-publisher/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./publisher/requirements.txt

    - name: Run Python script on .md change               
      run: |
        python3 ./publisher/main.py --login=${{ env.CONF_USER }} --password=${{ env.CONF_TOKEN }}

